### ISSUE TITLE
Building sedutil

### ISSUE THREAD

**Issue by davidepic91** [Drive-Trust-Alliance/sedutil#159] opened 2017-07-10 13:21 UTC
I'm trying to building sedutil for the first time. I followed instructions contained in "BUILDING" file which consists in these steps:
	cd ../LinuxPBA
	rm -rf dist
	make CONF=Release 
	make CONF=Release_x86_64
	make CONF=Debug 
	make CONF=Debug_x86_64
	cd ../images
        sudo ./buildUEFI64 Release

But I obtain the following:

+ . conf
++ TINYCORE=Core-6.4.1.iso
++ SYSLINUX=syslinux-6.03
++ TCDISTRO=http://distro.ibiblio.org/tinycorelinux/6.x/x86/
++ BUILDROOT=git://git.buildroot.net/buildroot
++ BUILDROOT_TAG=2015.11
++ git describe --dirty
fatal: Not a git repository (or any of the parent directories): .git
+ VERSIONINFO=
+ VERSIONINFO=downloaded
+ BUILDTYPE=Release
+ BUILDIMG=UEFI64_Release-downloaded.img
+ '[' Release == Debug ']'
+ '[' Release == Release ']'
+ echo 'Building ' Release image
Building  Release image
+ '[' -f scratch/syslinux-6.03/efi64/efi/syslinux.efi -a -f scratch/syslinux-6.03/efi64/com32/elflink/ldlinux/ldlinux.e64 -a -f ../LinuxPBA/dist/Release_x86_64/GNU-Linux/linuxpba -a -f ../linux/CLI/dist/Release_x86_64/GNU-Linux/sedutil-cli -a -f scratch/buildroot/PBA64/images/bzImage -a -f buildroot/syslinux.cfg ']'
+ echo ' prereqs are not available '
 prereqs are not available 
+ exit 1

**Comment by cristim** [comment] 2017-07-10 14:18
In the [sedutil/sedutil](https://github.com/sedutil/sedutil) fork we have support for building in Docker containers, please have a look [here](https://github.com/sedutil/sedutil/tree/master/images)

**Comment by davidepic91** [comment] 2017-07-10 14:54
Oh thanks ! I'm trying to use this. From the image directory, I perform the "Step 1"
"docker build -t sedutil ."
I obtain:
"Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
How can I solve this ? Sorry for my stupid questions but I'm new in this field.

**Comment by cristim** [comment] 2017-07-10 15:01
@davidepic91 you only need a working Docker setup.

This is a common issue if this your first time running it, likely you just need to run the docker command using sudo or add yourself to the docker group. Have a look [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04) for more instructions.

**Comment by davidepic91** [comment] 2017-07-10 16:53
Ok I will try to use a Docker as explained there. But, in general, I note the following:
- I launch ./getresources
- I copy "buildroot" folder inside "scratch"
- I edit "buildUEFI64" by commenting the check on the "prereqs".
After these steps, when I execute "./buildUEFI64 Release", the related image is created (I don't know if it is done in the correct way). What do you thing about this behavior ? Is there a way to create an image without using a Docker ?

**Comment by cristim** [comment] 2017-07-10 17:03
You shouldn't need to launch commands manually, just use those instructions and do it with Docker. Using Docker guarantees the images would be reproducible between various users, running the build commands manually may introduce human errors, differences or may simply fail to build.

If the image is working as expected, that should be it.

**Comment by davidepic91** [comment] 2017-07-11 16:27
Obviously my solution does not work. I installed Docker but I'm not confident with it.
When I execute "sudo docker build -t sedutil ." , I obtain the following

Sending build context to Docker daemon  300.5kB
Step 1/8 : FROM ubuntu:16.04
 ---> d355ed3537e9
Step 2/8 : RUN dpkg --add-architecture i386 && apt update && apt install -y         bc         build-essential         cpio         dosfstools         g++-multilib         gdisk         git-core         libncurses5-dev         libncurses5-dev:i386         python         squashfs-tools         sudo         unzip         wget         locales     && rm -rf /var/lib/apt/lists/*
 ---> Running in c823e29e9b91

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package cpio is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  tar

Package dosfstools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package bc
E: Unable to locate package build-essential
E: Package 'cpio' has no installation candidate
E: Package 'dosfstools' has no installation candidate
E: Unable to locate package g++-multilib
E: Couldn't find any package by regex 'g++-multilib'
E: Unable to locate package gdisk
E: Unable to locate package git-core
E: Unable to locate package libncurses5-dev
E: Unable to locate package libncurses5-dev:i386
E: Unable to locate package python
E: Unable to locate package squashfs-tools
E: Unable to locate package sudo
E: Unable to locate package unzip
E: Unable to locate package wget
E: Package 'locales' has no installation candidate
The command '/bin/sh -c dpkg --add-architecture i386 && apt update && apt install -y         bc         build-essential         cpio         dosfstools         g++-multilib         gdisk         git-core         libncurses5-dev         libncurses5-dev:i386         python         squashfs-tools         sudo         unzip         wget         locales     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by cristim** [comment] 2017-07-11 16:46
Looks like your docker setup is incorrect: `Temporary failure resolving 'archive.ubuntu.com'` indicates a DNS/networking issue

**Comment by davidepic91** [comment] 2017-07-12 09:34
Thank you, I followed the tutorial and now docker works in the correct way. Now, when I execute "sudo docker run --rm -it -v $PWD/../:/sedutil --privileged sedutil" there is the following problem: 
---------------------
+ cd scratch
+ rm -rf buildroot
+ git clone git://git.buildroot.net/buildroot
Cloning into 'buildroot'...
fatal: unable to connect to git.buildroot.net:
git.buildroot.net[0: 140.211.167.122]: errno=Connection timed out

+ die
+ echo An error has occured please fix this and start over
An error has occured please fix this and start over
+ exit 99
----------------------------------------------------------------------

I believe is due to the fact that in the "conf" file, there is "BUILDROOT=git://git.buildroot.net/buildroot" but it is no more reachable for some reason.

**Comment by davidepic91** [comment] 2017-07-12 09:42
Should I change it with "git://git.busybox.net/buildroot" or "https://git.busybox.net/buildroot" ?

**Comment by cristim** [comment] 2017-07-12 11:29
That looks as if the linuxpba binary was linked against the wrong C library. When running from the PBA image it has to be linked against uclibc, but your binary is apparently linked against glibc, likely from the container or from your host.

It may still be in the filesystem since you tried to build it manually before running from Docker. Can you create a completely clean build?

**Comment by davidepic91** [comment] 2017-07-12 15:53
Fine ! It works ! Thanks a lot ! Instead for the git repo path, I discover that "https://git.buildroot.net/buildroot" is useful when there is a firewall (that is my case). I have another question: is it possible to execute only ./buildUEFI64 without perform again all the operations (step 1 and 2) with the docker ? I tried but it does not work.

**Comment by cristim** [comment] 2017-07-12 17:15
Currently the build process starts from scratch, incremental building should be implemented eventually but it's not there yet

**Comment by davidepic91** [comment] 2017-07-12 17:57
Ok this means that if I want add some classes to the LinuxPBA (and then test them) I have to run again all the procedure. This is a nightmare because the "buildpbaroot" requires a lot of time, but if it is the only way... :-D
Instead, if we return to my first comment (original version without docker), I notice that the only missing file is "scratch/buildroot/PBA64/images/bzImage". In your opinion, is it a problem already discussed or concerns only my case ? Furthermore, also the original project (without docker) does not allow incremental building ?

**Comment by cristim** [comment] 2017-07-12 19:01
Yeah, it's not really rapid development, and also testing it requires flashing it to the target SSD or at least to an USB stick and power cycling the machine...

The bzimage is not the only one, there's stuff involving an embedded OS image which is being altered to include the linuxpba binary.

I never tried the pre-docker build, but I did manually try to execute some of the manual steps inside the running container, which is the closest you can get to an incremental build. But by default the build process has some steps which assume a clean slate and some steps which wipe out everything. This doesn't mean it can't be improved, it's just not done yet. If you're interested please give it a try and comment your progress on https://github.com/sedutil/sedutil/issues/9, and why not make a PR if you get far enough.

**Comment by davidepic91** [comment] 2017-07-13 07:35
Ok thanks ! My idea is to add some OpenSSL functionalities to the GetPassPhrase class. In your opinion, is it possible to add the OpenSSL libraries to the LinuxPBA ? If yes, do you know the basic steps in order to do this ? I think that I should change some MakeFile or something like that.

**Comment by cristim** [comment] 2017-07-13 08:08
@davidepic91 if you look under the hood the PBA Is simply a [Tiny Core Linux](http://distro.ibiblio.org/tinycorelinux/intro.html) image in which we inject the linuxpba binary compiled and linked against the same C library.

You could in theory inject more stuff, such as OpenSSL, but I would instead change the build process to use a full buildroot-based system to build the entire image from scratch, which gives much more flexibility.

**Comment by cristim** [comment] 2017-07-14 05:49
@davidepic91 we've just got a contribution implementing the incremental build support.

Huge thanks to @OliverO2!

**Comment by davidepic91** [comment] 2017-07-14 07:15
Great ! Thanks ! The command to execute a complete build is the following
"sudo docker run --rm -it -v $PWD/../:/sedutil --privileged sedutil autobuild.sh complete" ?
It does not work for me (Am I doing something wrong ?)

**Comment by OliverO2** [comment] 2017-07-14 08:01
@davidepic91 I suppose it does not work because your command line does not contain the complete (in-container) path for autobuild.sh. It would be easier to diagnose precisely if you had posted the resulting output.

Check the following:
* Your working directory must be `images`.
* Specify the complete path for `autobuild.sh`. It is best to copy the complete command line from the [images/README.md](https://github.com/sedutil/sedutil/blob/master/images/README.md)

**Comment by davidepic91** [comment] 2017-07-14 09:36
@OliverO2 Ok perfect ! If I perform a complete step, the procedure stops with the following:

VERSIONINFO=
VERSIONINFO=downloaded
BUILDTYPE=Release
BUILDIMG=UEFI64_Release-downloaded.img
'[' Release == Debug ']'
'[' Release == Release ']'
echo 'Building ' Release image
Building  Release image
'[' -f scratch/syslinux-6.03/efi64/efi/syslinux.efi -a -f scratch/syslinux-6.03/efi64/com32/elflink/ldlinux/ldlinux.e64 -a -f ../LinuxPBA/dist/Release_x86_64/GNU-Linux/linuxpba -a -f ../linux/CLI/dist/Release_x86_64/GNU-Linux/sedutil-cli -a -f scratch/buildroot/PBA64/images/bzImage -a -f buildroot/syslinux.cfg -a -f scratch/kmaps.tcz ']'
mkdir -p scratch/buildroot/PBA64/overlay/sbin/
cp ../LinuxPBA/dist/Release_x86_64/GNU-Linux/linuxpba scratch/buildroot/PBA64/overlay/sbin/linuxpba
cp ../linux/CLI/dist/Release_x86_64/GNU-Linux/sedutil-cli scratch/buildroot/PBA64/overlay/sbin/sedutil-cli
./buildUEFI64: line 39: scratch/buildroot/PBA64/overlay/etc/init.d/rcS: No such file or directory
echo '# Do not process /etc/init.d scripts'
./buildUEFI64: line 40: scratch/buildroot/PBA64/overlay/etc/init.d/rcK: No such file or directory

**Comment by OliverO2** [comment] 2017-07-14 11:18
@davidepic91 Looks like you have found a bug. Sorry for the inconvenience. I suggest we continue in [this thread](https://github.com/sedutil/sedutil/issues/18) where I have posted a fix for you to test.

**Comment by cristim** [comment] 2017-07-15 00:44
In https://github.com/sedutil/sedutil/issues/21 I started to refactor the buildsystem in order to remove the buildroot from the picture and just rely on TinyCore binary packages.

Any feedback, suggestions or code contributions are welcome.

**Comment by r0m30** [comment] 2017-07-20 22:07
I do wonder how you are going to resolve the clib/libstdC++ linking issue, that is the primary reason I've gone the other way and decided to rely on buildroot based PBA and rescue images.

I closing this as the topic seems to have changed to building the PBA in your fork.

**Closed by r0m30** 2017-07-20 22:07 UTC

**Comment by cristim** [comment] 2017-07-21 12:44
@r0m30 everything would be built inside a TinyCore Docker container matching the TinyCore image used as base for the new PBA/Rescue images.

The sedutil binaries would be packaged into TinyCore TCZ packages, which would be installed using the TinyCore package manager into the remastered image used as base of the PBA/Rescue.

All this build process would take a few minutes, about 20x times faster than the current buildroot build system.

For more details you can have a look at https://github.com/sedutil/sedutil/issues/21. If you are interested, we can continue this discussion there.
