### ISSUE TITLE
Scan fails to locate /dev/nvme0n1 

### ISSUE THREAD

**Issue by laser-beans** [Drive-Trust-Alliance/sedutil#101] opened 2016-11-14 05:55 UTC
I am having trouble with a new system on which I am trying to implement self-encryption.

Computer: Thinkpad P50
Hard-drive: Samsung MZVPV256HDGL (NVMe SSD with Opal 2.0)
OS: Arch Linux with kernel 4.8.7-1-ARCH

I have a UEFI/GPT 64-bit system, for which I have used the appropriate UEFI64_Release.img.gz and UEFI64_Debug.img.gz images.

I am using the most recent release of Sedutil, patched according to:
https://github.com/Drive-Trust-Alliance/sedutil/issues/55

Using `sedutil-cli --scan` only lists hard drives enumerated as /dev/sd*, and fails to identify my nvme drive enumerated as /dev/nvme0n1. Regardless, I am able to use `sedutil-cli --query /dev/nvme0n1`, which reports the drive is Opal-capable, as expected (see output below). Furthermore, I am able to set up the drive and enable locking without any errors, following the directions in the [documentation](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive).

However, since scan is unable to locate my drive, the PBA fails to unlock it. I attempted using the PBA test USB and then loading it to the actual drive, and neither was able to identify the nvme drive at boot time.

Does scan only look for drives enumerated as /dev/sd*? Is there any upstream fix coming?

Thanks for you work on this project!

Output of `# sedutil-cli --query /dev/nvme0n1`
```
/dev/nvme0n1 OTHER SAMSUNG MZVPV256HDGL-000L7               5L6QBXW7 S27MNY0HA01060      
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 16 (8192), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65540  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1

```

**Comment by r0m30** [comment] 2016-11-29 23:49
@laser-beans 
First a question for you, is that an OEM drive or were you able to purchase it retail?  I still do not have a nvme drive to test with.  The nvme code was donated to the project.

Yes the scan and PBA are currently only looking at /dev/sd[a-z].  I'm putting together an update now and will look into fixing this.  You say you patched your sedutil to include the new nvme headers.  If you can do a local build perhaps a quick fix would be to update linux/os.h and change the 
#define DEVICEMASK snprintf(devname,23,"/dev/sd%c",(char) 0x61+i)
to something like this
#define DEVICEMASK snprintf(devname,23,"/dev/nvme0%c",(char) 0x31+i)

A more robust fix will require changing the scan to be a method in DevOS and calling it instead of using the defined printf in os.h.  I'm not sure how much work that will be but I'll see if I can get something into the next release.

**Comment by gebart** [comment] 2016-12-05 23:24
@laser-beans 
I was in a similar situation as you. sedutil works fine on my NVMe drive for all commands where you specify the device node. Like you noticed, the drive responds on `--query`, but `--scan` doesn't know about `/dev/nvme0`.

The LinuxPBA has the same problem, it does not attempt to unlock NVMe drives, so I have created an alternative set of boot scripts which I posted at #106, https://github.com/gebart/opal-kexec-pba.

**Comment by laser-beans** [comment] 2016-12-12 07:10
I have an OEM drive. Let me know if you want me to do any testing.

Thanks for the suggestion, it works if you use:
#define DEVICEMASK snprintf(devname,23,"/dev/nvme%dn1",i)

If you are interested, I made a branch that can scan through all devices /dev/sd* and /dev/nvme* with minor edits:
#108

**Comment by eilersKevin** [comment] 2016-12-23 11:48
This is a pretty serious issue since it not only affects sedutil-cli but also the PBA, effectively locking out all users that follow the documentation to encrypt their NVME boot drive, until they boot into a rescue system and disable the locking.

**Comment by TuxmanLC** [comment] 2017-01-26 23:03
Replying with the hope of getting more traction on resolving this issue.

I'm having the same issues as OP with the retail version of Samsung 960 EVO 250GB. 'sedutil-cli --scan' doesn't find the NVMe drive, while 'sedutil-cli --query /dev/nvme0n1' finds the OPAL compatible drive. I'm delaying setting up the encryption password until the PBA image is fixed. Please help, thanks!

`$ sudo sedutil-cli --query /dev/nvme0n1

/dev/nvme0n1 OTHER Samsung SSD 960 EVO 250GB     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65540  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1`

**Comment by etfeet** [comment] 2017-02-19 23:12
I'm having this issue as well:

computer: dell xps 9350
drive: Samsung 960 pro 512gb NVMe (/dev/nvme0n1)
OS: arch linux - kernel 4.9.9

**Comment by yngman** [comment] 2017-04-13 16:26
I can confirm this bug on my system:
```
$ sudo sedutil-cli --scan
[sudo] password for root: 

Scanning for Opal compliant disks
/dev/sda No   
No more disks present ending scan
```
```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    1  29,8G  0 disk 
├─sda1        8:1    1   476M  0 part /run/media/user/ARCH_201703
└─sda2        8:2    1    64M  0 part 
nvme0n1     259:0    0 465,8G  0 disk 
├─nvme0n1p1 259:1    0     1G  0 part /boot
└─nvme0n1p2 259:2    0 464,8G  0 part /
```
```
$ sudo sedutil-cli --query /dev/nvme0n1

/dev/nvme0n1 OTHER Samsung SSD 960 EVO 500GB                1B7QCXE7 S3EUNX0J110885P     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65540  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
```

I'm lucky that I found this before commencing since I initially assumed this was a minor inconvenience. PBA not detecting my drive would obviously be much worse and a deal breaker. I am therefore also awaiting a fix before using SED.

May I suggest a note on this in the Wiki instructions on NVME drives?

**Comment by r0m30** [comment] 2017-07-19 00:34
NVMe support updated in v1.15

**Closed by r0m30** 2017-07-19 00:34 UTC
